/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambda.custom.runtime.java.example.runtime;

import org.junit.Test;
import static org.easymock.EasyMock.*;

import com.amazonaws.services.lambda.runtime.RequestHandler;

import org.easymock.EasyMockSupport;

public class LambdaInvocationPollerTest extends EasyMockSupport {
    @Test public void postsInvocationErrorOnExceptionInHandler() throws LambdaRuntimeError {
        final LambdaRuntimeInterface runtimeInterface = mock(LambdaRuntimeInterface.class);
        final RequestHandler<String, String> requestHandler = mock(RequestHandler.class);
        final LambdaInvocationPoller lambdaInvocationPoller = LambdaInvocationPoller.builder()
                .lambdaRuntimeInterface(runtimeInterface)
                .build();

        final RuntimeException error = new RuntimeException("");
        expect(runtimeInterface.getNextInvocation()).andReturn(LambdaInvocation.builder()
                .invocationEvent("")
                .context(LambdaContext.builder()
                        .awsRequestId("")
                        .build())
                .build());
        expect(requestHandler.handleRequest(anyString(), anyObject())).andThrow(error);
        runtimeInterface.postInvocationError(anyString(), eq(error));
        expectLastCall();
        replayAll();

        lambdaInvocationPoller.pollAndHandleInvocation(requestHandler);
        verifyAll();
    }
}
