/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambda.custom.runtime.java.example.runtime;

import org.junit.Test;
import static org.easymock.EasyMock.*;

import com.amazonaws.services.lambda.runtime.RequestHandler;

import org.easymock.EasyMockSupport;

public class LambdaRuntimeTest extends EasyMockSupport {
    @Test
    public void postsInitializationError() throws LambdaRuntimeError {
        final LambdaRuntimeInterface runtimeInterface = mock(LambdaRuntimeInterface.class);
        final RequestHandler<String, String> requestHandler = mock(RequestHandler.class);
        final LambdaInvocationPoller lambdaInvocationPoller = mock(LambdaInvocationPoller.class);
        final LambdaRuntime runtime = LambdaRuntime.builder()
                .lambdaRuntimeInterface(runtimeInterface)
                .lambdaInvocationPoller(lambdaInvocationPoller)
                .build();

        final LambdaRuntimeError error = new LambdaRuntimeError("");
        lambdaInvocationPoller.pollAndHandleInvocation(requestHandler);
        expectLastCall().andThrow(error);
        runtimeInterface.postInitializationError(error);
        expectLastCall();
        replayAll();

        runtime.initialize(requestHandler);
        verifyAll();
    }
}
